version: '3.9'

services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Mailjet Email Configuration (replaces SMTP)
      - MAILJET_API_KEY=${MAILJET_API_KEY}
      - MAILJET_SECRET_KEY=${MAILJET_SECRET_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
      - JWT_SECRET=${JWT_SECRET}
      - FLASK_API_URL=${FLASK_API_URL}
      - DO_SPACES_ENDPOINT=${DO_SPACES_ENDPOINT}
      - DO_SPACES_KEY=${DO_SPACES_KEY}
      - DO_SPACES_SECRET=${DO_SPACES_SECRET}
      - DO_SPACES_BUCKET=${DO_SPACES_BUCKET}
      - DO_SPACES_REGION=${DO_SPACES_REGION}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
      - redis
  db:
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - 6380:6379
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes
volumes:
  pgdata: {}
  redisdata: {}